name: SlackIntegration
main: slackintegration.Slack
version: @project.version@

commands:
  slack:
    default: op
    permission: slack.use
    usage: |
      /slack url [url]
      /slack port [port]
      /slack add <channel>
      /slack remove <channel>
      /slack channels
      /slack reload
      /slack format [format]
      /slack deaths [true|false]
      /slack achievements [true|false]